In [7]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [15]:
def transform1(sx, sy, syaw, gx, gy, gyaw):
    rot = np.array(
        [[math.cos(syaw), -math.sin(syaw)],
         [math.sin(syaw), math.cos(syaw)]]
        )
    p = np.array([sx, sy]).reshape((2,1))
    T = np.block(
        [[rot, p],
         [np.zeros((1,2)),1]]
    )
    print(np.linalg.inv(T)-np.block([[rot.T,np.zeros((2,1))],
                                      [np.zeros((1,2)),1]])@ np.block([[np.eye(2),-p],
                                       [np.zeros((1,2)),1]]))
    bG = np.linalg.inv(T) @ np.array([gx,gy,1.0])
    bx, by, btheta = bG[0], bG[1], gyaw-syaw
    return bx, by, btheta

In [16]:
x,y,theta = transform1(1, 1, 0.3, 5, 4, 0.2)

[[ 1.11022302e-16  5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [17]:
print(x,y,theta)

4.707906576486444 1.6839286407314602 -0.09999999999999998


In [18]:
def transform2(sx, sy, syaw, gx, gy, gyaw):
    theta1 = syaw
    dx = gx - sx
    dy = gy - sy
    new_x = dx * math.cos(theta1) + dy * math.sin(theta1)
    new_y = -dx * math.sin(theta1) + dy * math.cos(theta1)
    new_theta = gyaw-syaw
    return new_x, new_y, new_theta

In [19]:
x,y,theta = transform2(1, 1, 0.3, 5, 4, 0.2)
print(x,y,theta)

4.707906576486442 1.68392864073146 -0.09999999999999998
